# The Big Picture {#sec-big-picture}

## Vision - Where are we going?

>Team Core Values - Taken from the ADP Charter
Collaboration - conversation, not lecturing
Flexibility - kill your darlings for the greater good if necessary.
Respect - we are all professionals and should be treated as such.
Safety - the group space is safe for productive conflict
Humor - don't take anything too seriously
Kindness - don’t be a jerk

* What is the future state of the team? What does it look like?
* Answers the question: Where are you going?
* If there were no constraints at all, what would things look like in 5 years, 10 years, 20 years?
* What picture do we want to create for the future?
* What legacy do we want to leave behind?
Aim for a vivid picture of what the future looks like in 2-3 pages

What does success look like for the team?

## Purpose - Why do we do this?
Why does the team exist?
What is the inspiration that guides and motivates the team to achieve the mission?

## Mission - What do we do?
What the team aims to do to fulfill its purpose and acheive it's vision.

<!-- JJ EXAMPLE: Our mission is to provide the highest quality best available science for use in managing fisheries and marine resources.  -->

<!-- The FMA Analytical Services Team adheres to NOAA's mission of [Science, Service, and Stewardship](https://www.noaa.gov/our-mission-and-vision). -->

<!-- Science from the FMA A-Team:     -->

<!-- - is rigorous and quantitative;     -->
<!-- - based on statistics and evidence and;     -->
<!-- - aims for transparency & reproducibility. -->

<!-- Service from the FMA A-Team:     -->

<!-- - is to provide the best-available science for use in decision-making;    -->
<!-- - based on clear, consistent and effective communication and collaboration;     -->
<!-- - aims to share data, knowledge, and information -->

<!-- Stewardship from the FMA A-Team:     -->

<!-- - is to protect living marine resources, commercial fisheries, and the people who work in, on, or with marine ecosystems;     -->
<!-- - based on the diverse skill set and evolving abilities of the people and leveraged technologies and;     -->
<!-- - aims to be rational, ethical, and equitable. -->



## Internal Stakeholders

## External Stakeholders

## Culture & Values

* Share our learning and time with others on the team as well as those beyond our team, knowing that this builds community and ultimately improves both the quality and impact of our science.

<!-- # Lab culture and philosophy {#culture} -->

<!-- We approach our science with a common denominator of kindness. As part of our core lab culture, we:   -->

<!-- * __Ask for help, and share our learning__ -->
<!-- * __Make ourselves available__ -->
<!-- * __Come prepared and engage__  -->
<!-- * __Celebrate accomplishments (ours & those of others)__ -->
<!-- * __Sustain a positive, safe learning environment__ -->
<!-- * __Have an interdisciplinary (open) mindset__  -->
<!-- * __Are mindful of our own biases__ -->
<!-- * __Plan with intention, and follow through__ -->
<!-- * __Foster inclusivity within our group and greater community__ -->
<!-- * __Promote and sustain healthy work-life integration__ -->
<!-- * __Practice radical candor__ -->
<!-- * __Acknowledge and give credit to other lab member’s work__  -->

<!-- Though we do not expect incoming members to memorize everything, we do expect members to be aware of the group’s values.   -->

<!-- **Ask for help, and share your learning:** We are all learners, and most of our learning is done from each other. It is inefficient to struggle through problems alone. Ask for and give assistance with appropriate cognizance of the value of your time and the time of the person you are asking. You are not the first or last person to encounter a problem. When you identify a problem add an issue to the [lab issues repository](www.github.com/thefaylab/lab-chat), and update it with solutions when it is resolved. Also consider writing a tutorial/blog post for inclusion in our [lab’s shared resources](www.github.com/thefaylab/labhub), and share with the larger community by tweeting, leading and sharing at a lab meeting, or running a workshop (Quantfish woRkshop group, SouthCoast useR group, etc).   -->

<!-- **Make yourself available:** Be responsive to communication, and make time for things that address longer term goals, even when busy. For example, do not skip on things like attending seminars just because you have a big deadline looming (see note below on planning and organization). Note that being available does not mean that you are available 24/7 - this is not expected. Because as a group we value the role of collaboration and interaction in improving our work, it is expected that you be available in the lab/office during normal business hours for some time during the week (see section on attendance expectations).   -->

<!-- **Come prepared and be engaged:** Value your time. Be present during lab and individual meetings, and come to your work ready to do your work. Contribute and participate in planning and lab discussions. When it is your turn to run a meeting, come with an agenda and be prepared with questions. Aim to view meetings as events that contribute to your work and productivity, rather than taking away from them.   -->

<!-- **Celebrate accomplishments (yours & others):** You and your colleagues work hard. Things don’t always go exactly as you plan. Be supportive and proud of yourself and your peers when you accomplish things. We are not competing with each other - someone else’s success does not mean your failure. Share your accomplishments with others!   -->

<!-- **Sustain a positive, safe learning environment:** Everyone learns something for the first time at some time, and people learn in different ways. Expressing that you don’t know something is OK, and we understand that this can make someone feel vulnerable. We strive to maintain a culture that allows for and encourages this vulnerability. Community members should not be disparaged for not knowing things, and in addition, should not be disparaged for knowing things or wanting to learn.   -->

<!-- **Have an interdisciplinary (open) mindset:** We apply our work at the science-policy interface. This means we work on problems that span multiple disciplines. Co-creation of knowledge requires transdisciplinary approaches that can result in solutions that would not be possible with siloing. You will be collaborating with others who have different types of expertise, values, and terminology. Trust the expertise of others and actively seek feedback recognizing the importance of specialization.      -->

<!-- **Be mindful and aware of your own biases:** We all have biases that are inherent and can not be removed, but we can still work on both being less biased, and more aware of bias in ourselves and others. Periodically [check in on your biases](https://medium.com/better-humans/cognitive-bias-cheat-sheet-55a472476b18).   -->

<!-- **Plan with intention, and follow through:** Be organized and adaptable. Things don’t always go as planned and that’s OK. Planning can help you adapt when they don’t (see Come Prepared). Find a program/project management approach that works for you (see “How we work”); being organized can reduce stress immensely and help you progress with your goals.   -->

<!-- **Foster inclusivity within our group and greater community:** Part of our lab culture is that we are good citizens of our community, we take on leadership roles within SMAST and the University, we are supportive of others in our community during their milestones, we actively participate in SMAST events (e.g. the IMS graduate research symposium) and perform outreach. Work with Gavin when crafting your individual mentoring/development plans (see Chapter on Onboarding) to identify what you want to aim your efforts at.   -->

<!-- **Promote and sustain healthy work-life integration:** Our scientific research is not the only important thing in our lives, and publishing research is not the only mechanism by which to provide science and support our communities. We recognize the importance of our other commitments in keeping us healthy (mentally and physically) and bring our whole selves to our efforts. Try not to normalize overwork or being busy as achievement or status.   -->

<!-- **Practice radical candor:** We [care personally while also challenging directly](https://www.radicalcandor.com/). Be honest when communicating, accept critical (but kind) feedback, and give the same to others. View relationships within the group as collaborative rather than evaluative. Don’t take constructive criticism personally.   -->

<!-- **Acknowledge and give credit:** Working as part of a team, we will often (always?) be building on work done by others, receive assistance with work (see “Ask for help”), and using others’ words, code, content. Include acknowledgement and give credit for those contributions, in all forms of communication. We share content and code within the group with this expectation. One easy approach is to include hyperlinks to the work of others or their social media in your work. This also helps to amplify their voice and work as well as yours.   -->

