# Code of Conduct {#code}

A _Code of Conduct_ is a set of basic ground rules that we ask team members to follow. The goal is to create an open and inclusive space for our work that helps us achieve our collective goals. Along with our  [Big Picture](02-the-big-picture.qmd#sec-big_picture), a _Code of Conduct_    

  * provides a benchmark for self-evaluation    
  * helps define our identity    
  * establishes behavioral guidelines

__We expect all team members to adhere to the policies and guidelines outlined here, as well as those found in the [AFSC Code of Conduct](https://drive.google.com/file/d/1wV0g2Tea0jdPjsTeNNST7I871j70qLAw/view).__  

__*The FMA Analytical Services Team is dedicated to providing a harassment-free experience for everyone, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, age, race, or religion. We do not tolerate harassment of team members or others in our larger communities in any form.*__

This code of conduct applies to all A-Team spaces, including group and individual meetings (face to face and remote), workshops, email correspondence, chat and web channels, and code repositories. Anyone who violates this code of conduct may be sanctioned and referred to the AFSC's policies.

### Reporting

If you are being harassed by a member of the FMA A-Team, notice that someone else is being harassed, or have any other concerns, please contact the FMA Analytical Services Program Manager, Dr. Jason Jannot, at [jason.jannot@noaa.gov](mailto:jason.jannot@noaa.gov). If you do not feel comfortable reporting to Jason, please contact Jennifer Ferdinand (FMA Division Director) or Lisa Thompson (FMA Deputy Director) or any other AFSC supervisor.  Other methods of reporting available to you include:    

  * [NOAA Sexual Assault Sexual Harassment Helpline](https://noaasashhelpline.org/)
  * [NOAA Workplace Violence Prevention and Response Program](https://www.noaa.gov/workplace-violence-prevention-response-program)
  * [NOAA Workforce Management Office](mailto:DAO-955.OHCS@noaa.gov)
  * [NOAA Office of Inclusion and Civil Rights](mailto:noaa.oicr@noaa.gov)
 
  In addition to the AFSC's Code of Conduct, the Dec. 8th 2022 [Policy Statement on Equal Employment Opportunity](https://www.noaa.gov/organization/inclusion-and-civil-rights/policy-statement-on-equal-employment-opportunity) from NOAA provides a good explanation of NOAA's stance and policies against harassment, discrimination, and violence in the workplace.
