# Expectations {#expectations}

## Availability
Being available does not mean that you are available 24/7 - this is not expected. Do not expect responses to emails or any communication before or after regular business hours on weekdays (6 am - 5 pm), or on weekends/holidays/flex-days. However, because we recognize that A-Team members should be able to create a working schedule that is right for them, A-Team members will not be penalized for sending communication during these times.

## Google
### G-Mail
We communicate largely via email on the A-Team. You should therefore check your email at least once a day during the normal work week. 

### G-Calendar
Much of our work is communicating and much of that communication comes in the form of meetings. Therefore, you should:    

* [Make your calendar visible](999-appendix.qmd#sec-calendar) to others.    
* Keep your calendar up-to-date    
* Add your working location and hours    
* Add leave and out of office (OOO)    
* Set-up automated OOO messages with alternative contacts, if OOO for longer than 1 day   


## Attendance at regularly scheduled events

Attendance, either virtual or in-person, is reasonably expected at:

* Semimonthly A-Team meetings 
* Individual 1:1 with Jason (in-person when possible)
* Regularly scheduled project meetings  
* NPFM Council Meetings  
* FMA All-hands

Attendance is strongly recommended when possible at:    

* AFSC All-Hands    
* Other Center-wide Meetings


## Expectations for the Program Manager

As of `r format(Sys.Date(), "%Y")`, Jason Jannot is the FMA Analytical Program Manager.  You can read about his [leadership and management philosophy here](999-appendix.qmd#sec-jj-philosophy).

The Program Manager will (at a minimum) provide the A-Team with:  

* Clarity (the `why?`)
* Guidance (the `how?`)    
* Expectations (the `what?`)   
* Collaboration & Communication (the `who?`)
* Prioritization & Gate-keeping  
* Accountability    
* Visibility & Public Recognition    
* Removing Obstacles    
* Timely Administrative Support

In addition to the above, the Program Manager will (at a minimum) provide individual team members with:  

* Positive feedback & constructive criticism on work  
* Professional career support and development, including but not limited to:    
    * opportunities for    
        * training    
        * presenting (e.g., conferences, meetings, outreach, etc.)    
        * publishing
        * advancing (e.g., promotion, details, etc.)    
        * collaborating    
        * leading    
        * mentoring
* Regular meetings to discuss work & maintain progress on goals  
* Empathetic listening    
* Coaching

##  Team members

A-Team members will (at minimum): 

* share knowledge, experience, code, and time with other team members
* adopt a collaborative working mindset    
* adapt and be flexible, within reason    
* communicate clearly and effectively with team members and Program Manager
* communicate both successes and sticking points on a regular basis with the PM 

In addition, team members should remember that we are a government agency which means we serve the people of the United States.  Adopting a service mindset when approaching each other, stakeholders, partners, and collaborators will magnify our positive impacts on commercial fishing and the wider world. Remember, service is the 2^nd^ of the three NOAA mission's: [Science, **Service**, Stewardship](https://www.noaa.gov/our-mission-and-vision).

Some ways to adopt a service mindset:    

* Mentor others when appropriate, especially new team members    
* Serve as a role model    
* Serve as a resource for other members of the A-Team    
* Nominate your peers for their hard work and achievements - [AFSC Awards page](https://sites.google.com/noaa.gov/myafsc/administrative/workforce-management/awards).
* Participate in outreach activities


Project assignment will be a discussion between individuals and the PM, with input from the A-Team when necessary/appropriate. Specific individual projects, deliverables, duties will be reflected on [individual Performance Plans](04-onboarding.qmd#sec-perf). Other duties that team members might assume, depending on interest, time, Program/Division/Center priorities, and needs include (but are not limited to):

* leading and assisting in designated research projects  
* participation in professional development opportunities  
* developing and submitting research funding proposals  
* submitting and publishing NOAA Technical Memorandum and other reports    
* submitting and publishing peer-reviewed journal articles
* participating in outreach activities    
* attending scientific and professional conferences


## Team Collaboration and Communication

Although the Program Manager is your primary supervisor, everyone should always feel like they can reach out to anyone else on the A-team for help or collaboration.
