# Offboarding {#offboarding}

[AFSC Offboarding Checklist for Federal Staff](https://drive.google.com/file/d/17hBFFWaAImoVNqHfPJmoAKqGqs8rD1Q2/view?usp=sharing)

[AFSC Offboarding Checklist for Non-Federal Staff (contractors and affiliates)](https://drive.google.com/file/d/1BdNN2rvgwdyUAuk_9cOlRGw5_ik6K37Q/view?usp=sharing)

## Exit Interview

Set up a dedicated time to meet with the A-Team PM to talk about your time in FMA, and to go through the appropriate checklist above. Besides the checklist, things to talk about include the best part of being part of the FMA A-Team, whether you got the support you needed and what could we improve for someone in your role in the future.

## Project Documentation

Project work should be hosted in the [A-Team Github repository](https://github.com/Alaska-Fisheries-Monitoring-Analytics) and saved on the `FMA Analytics Group` Google drive.

Each project should have an easily found README text file that provides information for others so they can navigate and use your work, and give contact information for authors (and any data creators/use restrictions if confidential data). Ideally, the README should also include links to publications and presentations from the work.

## Publications and Presentations

Ensure that publications and presentations from your projects are archived in the appropriate folder in the `FMA Analytics Group` Google drive.

## Data

Data used in support of your projects should be:

  * Saved in appropriate, non-proprietary format with accompanying metadata
  * **Not** included/hosted on github or any other public repository (unless non-confidential/anonymized)    
  * Accessible to A-Team members. 
  * Briefly described in the project README.

## Code

Code used or developed for your projects should be:

  * complete and well-documented, including information in a README about what each file does and workflow to run the code.
  *  hosted in the [A-Team Github repository](https://github.com/Alaska-Fisheries-Monitoring-Analytics) and saved on the `FMA Analytics Group` Google drive.

## Turning in equipment

Return all equipment (e.g., computer and peripherals) you have been using to the A-Team PM. Ensure all office furniture is present and remains in your office.

## Terminating Access

* Access to your `@noaa.gov` account will terminate on your last day.  [Transfer ownership of Google Docs](https://support.google.com/docs/answer/2494892?hl=en&co=GENIE.Platform%3DDesktop) to the A-Team PM.

* CAC access to the NOAA facilities and computers will be terminated when you leave Federal service. Ensure you have all your personal belongings prior to your last day.    
