# Resources {#sec-resources}

## NOAA

[NOAA's Vision and Mission](https://www.noaa.gov/our-mission-and-vision)

### AFSC

[AFSC Intranet](https://sites.google.com/noaa.gov/myafsc)

#### Strategic Science Plans
AFSC Strategic Science Plans define vision, mission, core values, goals and objectives for a 5 year period.    
[FY2023-FY2027](https://drive.google.com/file/d/1m3KldIXozp1mSH-VwzSFw0F35kuVaojx/view)

#### Annual Guidance Memos
Annual Guidance Memorandums prioritize activities for a single year to meet the objectives in the Strategic Science Plan.    
[FY2024](https://drive.google.com/file/d/1aMWiMJYuM8pueNbeHaLJoRBG6VlzTFYP/view)    
[FY2023](https://drive.google.com/file/d/1EuLPPk031l8KWI1bVu-W0F3H9waHoRK4/view)

#### FMA

Overview of the North Pacific Observer Program ([NPOP](https://www.fisheries.noaa.gov/alaska/fisheries-observers/north-pacific-observer-program))

[Activity Plans](https://drive.google.com/drive/folders/1LzUtltFG2Z-vLy5vbFF0dkA6B4bQOHh9)

## Psychological Safety {#psych-safety}

### Summaries/handouts
  
* The [Openscapes talk on Psychological Safety](https://docs.google.com/presentation/d/1TwCyf9xicLWBfPhW9HnYQH3-mHycEyVKTm38zSg4D3Q/edit?usp=sharing) in open data science teams by Tara Robertson (there is also a resource list at the end of this slide deck!)    
* [Worksheet](https://drive.google.com/file/d/1kY4otiCfyGXMHPtWxuSMndHsAbc5FcrY/view?usp=sharing) from NOAA Psychological Safety training    

### Books

* [Feminist Fight Club](https://bookshop.org/p/books/feminist-fight-club-a-survival-manual-for-a-sexist-workplace-jessica-bennett/6437314?ean=9780062689030) talks about how members of the group can hand the mic back if it's taken away, giving credit, support quieter members, etc.  It is focused on women supporting women, not Psych Safety specifically.    

* [This Chair Rocks](https://bookshop.org/p/books/this-chair-rocks-a-manifesto-against-ageism-ashton-applewhite/6986118?ean=9781250297259) by Ashton Applewhite (and her [TED talk](https://www.ted.com/talks/ashton_applewhite_let_s_end_ageism) [12 mins])    

### Studies

* Canadian study “[The Tallest Poppy](https://www.womenofinfluence.ca/tps/)” from the Women of Influence group    

* Paper: “[Know Before You Go: A Community-Derived Approach to Planning for and Preventing Sexual Harassment at Oceanographic Field Sites](https://doi.org/10.5670/oceanog.2023.112).”

### Videos
Brene Brown’s [TED talk on vulnerability](https://brenebrown.com/videos/ted-talk-the-power-of-vulnerability/) (20 mins)


