# Wellness Resources
NOAA provides an array of resources in the area of health and
wellness.    

a. [NOAA ADR Program](https://www.noaa.gov/organization/administration/nao-202-715-noaa-alternate-dispute-resolution-program) uses two approaches for early intervention and dispute resolution, which are mediation and facilitated problem-solving.    

b. Federal Occupational Health (FOH) supports programs to improve the health, safety, and productivity of the federal workforce through webinars and activities (i.e., Creating Belonging through Psychological Safety, Social Security Retirement, etc.).    

c. [Mindful NOAA](https://sites.google.com/noaa.gov/mindful-noaa-collaboration/home?authuser=0) offers mindfulness practices and educational opportunities to improve workplace culture through employee health, resilience, performance, and leadership.    

d. [Reasonable Accommodations](https://sites.google.com/noaa.gov/ohcs/employee-resources/work-life-resources/workplace-programs/reasonable-accommodations) allows employees to request a change or modification in the work environment or in the way things are customarily done.    

e. NOAA Nursing Mother’s Program serves to offer the emotional support and worksite assistance nursing mothers need as they transition back into the workplace.    

f. [NOAA Workplace Violence Prevention & Response Program](https://www.noaa.gov/workplace-violence-prevention-response-program) works to establish a culture of professionalism and respect through: violence prevention and response; education and training; victim support; reporting procedures; and appropriate accountability that enhances the safety and well-being of all NOAA employees, affiliates, and visitors.    

g. [NOAA Sexual Assault Sexual Harassment (SASH)](https://www.noaa.gov/organization/administration/nao-202-1106-noaa-sexual-assault-and-sexual-harassment-prevention-and) offers a helpline phone: 866-288-
6555, option 1, text: 202-335-0265, [NOAA online chat](https://noaasashhelpline.org/), and reporting email:
noaa.victimservices@noaa.gov.    

i. [WorkLife4You](https://sites.google.com/noaa.gov/ohcs/employee-resources/work-life-resources/workplace-programs/worklife4you) helps you and your household better manage daily responsibilities and life events.    

j. [Drug Free Workplace](https://sites.google.com/noaa.gov/ohcs/employee-resources/work-life-resources/workplace-programs/drug-free-workplace-program) is a condition of employment for all federal employees to refrain
from using illegal drugs on or off-duty.    

k. [Employee Assistance Program (EAP)](https://sites.google.com/noaa.gov/ohcs/employee-resources/work-life-resources/workplace-programs/employee-assistance-program-eap) provides services — including counseling sessions and advice on a wide range of issues — to create a positive and productive work environment for all employees and their managers.    

l. [NOAA Behavioral Health and Wellness](https://sites.google.com/noaa.gov/behavioral-health-and-wellness/home) provides training, information, services, and resources on a wide range of behavioral health and wellness topics.
