date: last-modified
description: "This is the manual for the Analytical Services Team, Fisheries Monitoring and Analysis Division, Alaska Fisheries Sceince Center, NOAA Fisheries"

project:
  type: website
  output-dir: _site

links:
  - label: <i class="fab fa-github fa-lg"></i> GitHub
    url: "https://github.com/jjannot-NOAA"

format:
  html:
    toc: true
    toc-location: left

website:
  title: FMA A-Team Manual
  site-url: https://Alaska-Fisheries-Monitoring-Analytics.github.io/manual/
  repo-url: https://github.com/Alaska-Fisheries-Monitoring-Analytics/
  repo-actions: [edit,issue]
  favicon: FMAnalytics_logo_pic.png
  navbar:
    title: false
    left:
        - text: Intro
          href: 01-intro.qmd
        - text: "Big Picture"
          href: 02-mission-goals.qmd
        - text: Conduct
          href: 03-code-of-conduct.qmd
        - text: Onboard
          href: 04-onboarding.qmd
        - text: Roles
          href: 05-roles-responsibilities.qmd
        - text: Comms
          href: 06-communication.qmd
        - text: Computing
          href: 07-computing.qmd
        - text: Projects
          href: 08-projects.qmd
        - text: Offboard
          href: 09-offboarding.qmd
        - text: Resources
          href: 10-resources.qmd
    tools:
      - icon: house-door-fill
        href: index.qmd
      - icon: github
        href: "https://github.com/Alaska-Fisheries-Monitoring-Analytics/"

bibliography: [references.bib]

page-footer:
    background: light
    left: |
      <a href="https://www.fisheries.noaa.gov/about/fisheries-monitoring-and-analysis">FMA AFSC NOAA</a>
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
