engine: knitr
project:
  type: book
  output-dir: _book

book:
  title: FMA A-Team Manual
  author: "Analytical Services\\\nFisheries Monitoring and Analaysis\\\nAFSC, NOAA Fisheries"
  date: last-modified
  cover-image: _img/FMAnalytics_logo_pic.png
  favicon: _img/FMAnalytics_logo_pic.png
  downloads: [pdf, epub]
  site-url: https://Alaska-Fisheries-Monitoring-Analytics.github.io/manual/
  repo-url: https://github.com/Alaska-Fisheries-Monitoring-Analytics/
  repo-actions: [edit,issue]
  chapters:
    - text: Home
      href: index.qmd
    - intro.qmd
    - the-big-picture.qmd
    - code-of-conduct.qmd
    - onboarding.qmd
    - expectations.qmd
    - communication.qmd
    - collaborate.qmd
    - publications.qmd
    - offboarding.qmd
  appendices:
    - text: Psychological Safety
      href: psychological-safety-resources.qmd
    - text: Wellness Resources
      href: wellness-resources.qmd
    - text: Alaska Fishery Background
      href: fishery-background.qmd
    - text: Observer Training Classes
      href: observer-training-classes.qmd
    - text: NOAA, AFSC, FMA Resources
      href: NOAA-AFSC-FMA-resources.qmd
    - text: Git Tips
      href: more-git.qmd
    - text: Jason's Philosophy
      href: jjphilosophy.qmd
    - text: Make Your Calendar Visible
      href: make-calendar-visible.qmd
    - text: Acronyms
      href: acronyms.qmd
  sidebar:
    contents: auto
    bread-crumbs: true
  page-navigation: true
  version: 1.0

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    page-footer:
      background: light
      left: |
        <a href="https://www.fisheries.noaa.gov/about/fisheries-monitoring-and-analysis">FMA AFSC NOAA</a>
      right: |
        This book was built with <a href="https://quarto.org/">Quarto</a>.
    cover-image: _img/FMAnalytics_logo_pic.png
    favicon: _img/FMAnalytics_logo_pic.png
    embed-resouces: true
    number-depth: 0
  pdf:
    documentclass: scrreprt
    colorlinks: true
    number-sections: false
    indent: false

