engine: knitr
project:
  type: book
  output-dir: _book

book:
  title: FMA A-Team Manual
  author: "Analytical Services\\\nFisheries Monitoring and Analaysis\\\nAFSC, NOAA Fisheries"
  date: last-modified
  cover-image: _img/FMAnalytics_logo_pic.png
  favicon: _img/FMAnalytics_logo_pic.png
  downloads: [pdf, epub]
  site-url: https://Alaska-Fisheries-Monitoring-Analytics.github.io/manual/
  repo-url: https://github.com/Alaska-Fisheries-Monitoring-Analytics/
  repo-actions: [edit,issue]
  chapters:
    - text: Home
      href: index.qmd
    - 01-intro.qmd
    - 02-the-big-picture.qmd
    - 03-code-of-conduct.qmd
    - 04-onboarding.qmd
    - 05-expectations.qmd
    - 06-communication.qmd
    - 07-projects.qmd
    - 071-collaborate.qmd
    - 08-offboarding.qmd
  appendices:
    - text: Psychological Safety
      href: 999-psychological-safety-resources.qmd
    - text: Alaska Fishery Background
      href: 999-fishery-background.qmd
    - text: Observer Training Classes
      href: 999-observer-training-classes.qmd
    - text: NOAA, AFSC, FMA Resources
      href: 999-NOAA-AFSC-FMA-resources.qmd
    - text: Git Tips
      href: 999-more-git.qmd
    - text: Jason's Philosophy
      href: 999-jjphilosophy.qmd
    - text: Make Your Calendar Visible
      href: 999-make-calendar-visible.qmd
    - text: Acronyms
      href: 999-acronyms.qmd
  sidebar:
    contents: auto
    bread-crumbs: true
  page-navigation: true
  version: 1.0

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
    page-footer:
      background: light
      left: |
        <a href="https://www.fisheries.noaa.gov/about/fisheries-monitoring-and-analysis">FMA AFSC NOAA</a>
      right: |
        This book was built with <a href="https://quarto.org/">Quarto</a>.
    cover-image: _img/FMAnalytics_logo_pic.png
    favicon: _img/FMAnalytics_logo_pic.png
    embed-resouces: true
    number-depth: 0
  pdf:
    documentclass: scrreprt
    colorlinks: true
    number-sections: false
    indent: false

