---
title: "Contributing"
author: "Jason E. Jannot"
date: "`r Sys.Date()`"
output:
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# How to Contribute

This document describes how to contribute to this project.

- Great to have you here.
- You can help make this project better!
- Thank you for your efforts.


## Code of Conduct
This project and everyone participating in it is governed by the [AFSC Code of Conduct](https://sites.google.com/noaa.gov/myafsc/home/about-afsc) as well as the [Github and Git Guidance and Best Practices for NMFS Users](https://nmfs-opensci.github.io/GitHub-Guide/).  By contributing to this project you agree to abide by these terms.

## Team members

**Lead**: Jason E. Jannot, NOAA Fisheries AFSC FMA Division, Seattle, WA.    

**Contributors**:

* Jennifer Cahalan, Pacific States Marine Fisheries Commission and AFSC FMA Division, Seattle, WA 

* Craig Faunce, NOAA Fisheries AFSC FMA Division, Seattle, WA

* Christian Gredzens, NOAA Fisheries AFSC FMA Division, Seattle, WA

* Andy Kingham, NOAA Fisheries AFSC FMA Division, Seattle, WA

* Geoff Mayhew, NOAA Fisheries AFSC FMA Division, Seattle, WA

* Cameron Van Horn, Pacific States Marine Fisheries Commission and AFSC FMA Division, Seattle, WA 

## Getting Started
* Make sure you have a GitHub account.
* Clone the repository from GitHub to your local machine.
* Questions? email jason.jannot@noaa.gov

## Git Workflow for Collaborating

A Git workflow is a recommendation for how to use Git to accomplish work in a consistent and productive manner. The goals is that the workflow enhances the effectiveness of the team and does not limit productivity. A good workflow proactively reduces the number of merge conflicts and merges that need to be reverted. The choice of workflow by a team should be a joint decision.  Jason's recommendation is to use the [GitFlow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) workflow because it accomplishes two important, but somewhat competing, tactics to reduce merge conflicts when collaborating with git:

  1. **Branch life should be minimized**
The risk of merge conflicts increase in proportion to the time the branch has been separate from the main branch. Short-lived branches promote cleaner merges.

  2. **Branches should be tested before merging**
Testing a branch before merging into the main branch reduces problems. However, accidents happen, thus a good workflow allows for easy reverts that don't cause issues for other contributors.

*Having said all that, I welcome all discussions on how to best develop our Git workflow!* - Jason.

For those interested a comparison of Git workflows can be found [here](https://www.atlassian.com/git/tutorials/comparing-workflows).

## Data
No PII or BII data or data that could identify fishers, individual fishing locations, or individual processors should be saved to this repository.  Any such data will be removed immediately.  For further guidance see: [Github and Git Guidance and Best Practices for NMFS Users](https://nmfs-opensci.github.io/GitHub-Guide/).

## Fixing typos

You can fix typos, spelling mistakes, or grammatical errors in the documentation directly using the GitHub web interface, as long as the changes are made in the _source_ file. 
This generally means you'll need to edit [roxygen2 comments](https://roxygen2.r-lib.org/articles/roxygen2.html) in an `.R`, not a `.Rd` file. 
You can find the `.R` file that generates the `.Rd` by reading the comment in the first line.

## Bigger changes

If you want to make a bigger change, it's a good idea to first file an issue and make sure someone from the team agrees that it’s needed. 
If you’ve found a bug, please file an issue that illustrates the bug with a minimal 
[reprex](https://www.tidyverse.org/help/#reprex) (this will also help you write a unit test, if needed).
See the tidyverse guide on [how to create a great issue](https://code-review.tidyverse.org/issues/) for more advice.
Other sources for issue best practices are described in various places on the web, such as [here](https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f) and [here](https://rewind.com/blog/best-practices-for-using-github-issues/).
  

## Making Changes
The following uses the Gitflow method as the workflow.

* Clone the package onto your computer. If you haven't done this before, we recommend using `usethis::create_from_github("jjannot-NOAA/AnnualReportADPGantt", fork = TRUE)`.
* Pull the most recent code.
* Create a Git branch for your pull request (PR). We recommend using `usethis::pr_init("brief-description-of-change")`.
* Make your changes.
* Commit your changes. See the [Git Commit Messages] styleguide below.
* Push your changes to the remote Github repository.
* Go to Github and create a 'pull request' e.g., by running `usethis::pr_push()`, and following the prompts in your browser. The title of your PR should briefly describe the change.See the [Pull Requests Messages] section below.
* Assign a reviewer.    
  
## Styleguides

### Git Commit Messages
As a general rule, you should commit when you finish something that allows your code to work - usually ends up being a couple times an hour.

* Use the present tense ("Add feature" not "Added feature")
* Use the imperative mood ("Move cursor to..." not "Moves cursor to...")
* Limit the first line to 72 characters or less
* Reference issues and pull requests liberally after the first line

### Pull Requests Messages
 For general guidelines, please see [Github's Pull Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) page.
 
In the message, please include the following headers:

* Description of the Issue or New Feature
* Description of What Has Been Done
* Usage
  * Examples and/or how others might test the change
* Assign a Reviewer - this will most likely be the Merge Master.  In the case of the Merge Master, this will be another appropriate contributor.

### Coding conventions
Start reading our code and you'll get the hang of it. We optimize for readability.

  * Scripts should not be longer than 400-600 lines.
  
  * We use [roxygen2](https://cran.r-project.org/package=roxygen2), with [Markdown syntax](https://cran.r-project.org/web/packages/roxygen2/vignettes/rd-formatting.html), for documentation.  

  * Never use `rm(list = ls())` Why, you ask? Well first off, Jenny Bryan is likely to come [set your computer on fire](https://www.tidyverse.org/blog/2017/12/workflow-vs-script/).  More specifically, it mixes *your* workflow (i.e., personal choices) with *the* product (i.e., the R code needed by someone else to run your code).  See Jenny's in-depth discussion at the link above.

  * Write functions. There's a good chance that your script can be simplified into a function. "Everything that happens is a function call." - John Chambers
  
  * Always put spaces after list items and method parameters (1, 2, 3, not 1,2,3) and around operators (x + y = 1, not x+y=1).

  * Eliminate unnecessary white space.  I realize this conflicts with the previous statement, but I'm comfortable with that ambiguity.

  * Use a styler and IDE to keep your code clean.  [`stylr`](https://styler.r-lib.org/) is a good R package for keeping your code tidy and easy to use.
  
  * `tidyverse` methods, especially those using pipes, `%>%`, increase readability and make reviewing code much more pleasant.
  
  * When in doubt, consult the [`tidyverse` style guide](https://style.tidyverse.org/)
  
This is collaborative software. Consider the people who will read your code, and make it look nice for them. It's sort of like driving a car: Perhaps you love doing donuts when you're alone, but with passengers the goal is to make the ride as smooth as possible.

### File structure and conventions
Keeping a tidy project requires maintaining order amongst files.

  * General folder structure is:
    * -- root
        * -- data
        * -- figures
        * -- notes
        * -- R
        * -- scripts
        * -- tables
        * -- tests (optional)
      
  * root directory in addition to holding the folders (above), should only contain configuration and R package files.
  
  * data - holds any data files used in the project.
  
  * figures - holds any figure files created by the project.
  
  * notes - holds `TODO.Rmd`, `Notes.Rmd`, `SCRATCH.R/.Rmd` and reusable templates (for Roxygenating functions, headers for commenting code) or example code.  The `TODO.Rmd` is being worked on and what has recently been done and should closely mirror Git commits. `Notes.Rmd` is more narrative than `TODO` and contains important information that is too detailed/complex for a vignette.  Scratch files are sandboxes for working out code.
  
  * R - should hold only functions.  Each function should be called `<my-special-function-name>_function.R`.
  
  * scripts - these are the scripts that run the analysis.  Each script name should start with a number in the order the scripts are to be run.  The first script in the sequence is typically `0_Setup.R`.  `Setup.R` sets the paths for the project (this makes it reproducible on your machine!), loads all necessary libraries, date constants, functions, and data. The next script in the sequence might be, e.g., `1_Pre_Processing.R`, followed by `2_Data_Wrangling.R`, `3_Analysis.R`, `4_Plots.R`...note: these are just examples.
  
  * tables - holds any tables generated by the scripts.
  
  * tests - any unit tests that might be applicable. This is optional.
  
## Reviewing Pull Requests
  * Open the pull request
  * Review the code changes
  * Reviewer - provide comments and feedback in GitHub
  * Originator - respond to comments, perhaps add comments
  * Approve changes (upper right corner) and add approval comment
  * **Merge Master/Code owner merges all pull requests! Please do not merge your own pull request.** If the Merge Master is pushing code, then the reviewer should be responsible for merging the pull request.
  * MergeMaster will delete the branch once the code has been merged.
  * **DONT FORGET TO PULL the new code** to your local instance to get latest code.

 
<!-- # Documentation -->

<!-- This section includes any help you need with the documentation and where it can be found. Code needs explanation, and sometimes those who know the code well have trouble explaining it to someone just getting into it.  -->

<!-- * Help us with documentation here -->

* If you have further questions, contact: Jason Jannot jason.jannot@noaa.gov
