---
title: "Facilities"
---
AFSC buildings on the Seattle Sand Point Campus (a.k.a. [Western Regional Center \[WRC\]](https://www.wrc.noaa.gov/)) are only accessible during work hours and with a CAC.

[Map of NOAA Sand Point Seattle Campus](https://www.wrc.noaa.gov/images/WRC_Map.jpg)

There is a cafeteria in Building 2 that offers snacks and drinks (coffee, tea, etc.). Full lunch meals are no longer offered. As of `r Sys.Date()` WRC is experimenting with food trucks on campus on T,W, & Th, 1100-1330, located in the upper parking lot of Building 3. Eventually there will be a Food Truck calendar.

### Office space

Our physical offices are in Building 4 of the WRC.    
The following are FMA A-Team (and affiliated staff) office numbers:    

* 1060 - [Jason Jannot, FMA Analytical Services Program Manager](https://www.fisheries.noaa.gov/contact/jason-e-jannot)
* 1065 - Cameron Van Horn, Data Management Specialist, PSMFC
* 1065 - Christian Gredzens, Research Fishery Biologist, NOAA
* 1057 - Andy Kingham, Operations Analyst, NOAA
* 1057 - Geoff Mayhew, Research Fishery Biologist, NOAA
* 1056 - [Craig Faunce, Research Fisheries, NOAA  Biologist](https://www.fisheries.noaa.gov/contact/craig-h-faunce)
* 1089 - Jennifer Cahalan, Statistician/Analyst, PSMFC    

**Affiliated staff**    

* Lacey Jeroue, AMMOP Program Manager, PSMFC    
* Alaska Regional Office (AKRO) Juneau A-Team collaborators    
    
    * [Phil Ganz](https://www.fisheries.noaa.gov/contact/phil-ganz)    
    * [Jason Gasper](https://www.fisheries.noaa.gov/contact/jason-gasper-phd)    
    * [Jennifer Mondragon](https://www.fisheries.noaa.gov/contact/jennifer-mondragon)   
  
Other FMA staff offices

* 1059 - [Jennifer Ferdinand, FMA Division Director](https://www.fisheries.noaa.gov/contact/jennifer-ferdinand)
* 1061 - [Lisa Thompson, FMA Deputy Director](https://www.fisheries.noaa.gov/contact/lisa-thompson)
* 1062 - [Marlon Conception, FMA Debriefing Program Manager](https://www.fisheries.noaa.gov/contact/marlon-concepcion)
* 1063 - [Brian Mason, FMA Training Program Manager](https://www.fisheries.noaa.gov/contact/brian-mason)


### Reservations - Rooms & Vehicles
   Reservations for rooms or government vehicles can be found [here](https://sites.google.com/noaa.gov/myafsc/reservations)
   
### Parking
To obtain either a vehicle or a bike parking pass for the Seattle Sand Point Campus, contact Pass & ID Security Office in Building 1 (206-526-6571). You will need to fill out a [WRC Parking Form](http://www.google.com/url?q=http%3A%2F%2Fwww.wrc.noaa.gov%2Fforms%2FWRC%2520Parking%2520Decal%2520v2008a.pdf&sa=D&sntz=1&usg=AOvVaw2YdnFqmKoV029T-pt6UwFj).


### Transit Benefits for Bicyclists
#### Federal employees only
Allows for reimbursement to employees who use a non-motorized bicycle for a substantial portion of travel between your residence and the work site. Reimbursement can be up to $20 per month, not to exceed $240 per calendar year for bicycle commuting expenses.

[More information on bike benefits and instructions](https://sites.google.com/noaa.gov/cao/about-ocao/logistics-operations-division/noaa-transit-subsidy-program).

### Transportation Subsidy
#### Federal employees only
NOAA offers this non-taxable transit-fare subsidy program to encourage federal employees to use public mass transportation while commuting to and from work.  Qualified employees are provided with a monthly benefit based on the distance to and from work. The monthly maximum subsidy transit benefit allowance is $270. Unused benefits do not carry over to the next month.  

[More information on the transit subsidy program and application.](https://sites.google.com/noaa.gov/cao/about-ocao/logistics-operations-division/noaa-transit-subsidy-program)
